try changing invalidations workflow once more

diff --git a/.github/workflows/Invalidations.yml b/.github/workflows/Invalidations.yml
--- a/.github/workflows/Invalidations.yml
+++ b/.github/workflows/Invalidations.yml
@@ -1,71 +1,33 @@
-name: "Invalidations Check"
-
-on:
-  workflow_call:
-    inputs:
-      run-on-non-default-branches:
-        description: "Run on branches that are not the default branch as well"
-        default: false
-        required: false
-        type: boolean
-      directory:
-        description: "The directory on which JuliaFormatter needs to be run"
-        default: "."
-        required: false
-        type: string
-      julia-version:
-        description: "Julia version"
-        default: "1"
-        required: false
-        type: string
-      concurrent-jobs:
-        description: "Run jobs concurrently"
-        default: false
-        required: false
-        type: boolean
-      cancel-in-progress:
-        description: "Cancel jobs in-progress in favor of a new one in the same concurrency group"
-        default: true
-        required: false
-        type: boolean
-
-concurrency:
-  group: "${{ inputs.concurrent-jobs && github.run_id || github.ref  }}:${{ github.workflow }}"
-  cancel-in-progress: ${{ !inputs.concurrent-jobs && inputs.cancel-in-progress }}
+name: Invalidations
+on: pull_request
 
 jobs:
-  evaluate-invalidations:
-    if: ${{ inputs.run-on-non-default-branches || github.base_ref == github.event.repository.default_branch }}
+  evaluate:
     runs-on: ubuntu-latest
     steps:
     - uses: julia-actions/setup-julia@v2
       with:
-        version: '${{ inputs.julia-version }}'
+        version: '1'
+    - uses: actions/checkout@v4
+    - uses: julia-actions/julia-buildpkg@latest
+    - uses: julia-actions/julia-invalidations@v1
+      id: invs_pr
 
-    - name: "Checkout ${{ github.repository }}#${{ github.head_ref || github.ref_name }}"
-      uses: actions/checkout@v4
-    - uses: julia-actions/julia-buildpkg@v1
-    - name: "Count invalidations in PR"
-      id: invalidations-in-pr
-      uses: julia-actions/julia-invalidations@v1
-
-    - name: "Checkout ${{ github.repository }}#${{ github.event.repository.default_branch }}"
-      uses: actions/checkout@v4
+    - uses: actions/checkout@v4
       with:
-        ref: "${{ github.event.repository.default_branch }}"
-    - uses: julia-actions/julia-buildpkg@v1
-    - name: "Count baseline invalidations"
-      id: invalidations-baseline
-      uses: julia-actions/julia-invalidations@v1
+        ref: 'master'
+    - uses: julia-actions/julia-buildpkg@latest
+    - uses: julia-actions/julia-invalidations@v1
+      id: invs_master
 
-    - name: "Report invalidation counts"
+    - name: Report invalidation counts
       run: |
-        echo "Invalidations on ${{ github.event.repository.default_branch }}: ${{ steps.invalidations-baseline.outputs.total }} (${{ steps.invalidations-baseline.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
-        echo "Invalidations on ${{ github.head_ref || github.ref_name }}: ${{ steps.invalidations-in-pr.outputs.total }} (${{ steps.invalidations-in-pr.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
-
-    - name: "Check if the PR increases the number of invalidations"
+        echo "Invalidations on master: ${{ steps.invs_master.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps)"
+        echo "This branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
+      shell: bash
+    - name: PR doesn't increase number of invalidations
       run: |
-        if [ ${{ steps.invalidations-in-pr.outputs.total }} -gt ${{ steps.invalidations-baseline.outputs.total }} ]; then
-          echo "More invalidations have been introduced."
-          exit 1
+        if (( ${{ steps.invs_pr.outputs.total }} > ${{ steps.invs_master.outputs.total }} )); then
+            exit 1
         fi
+      shell: bash
