try other invalidations workflow

diff --git a/.github/workflows/Invalidations.yml b/.github/workflows/Invalidations.yml
--- a/.github/workflows/Invalidations.yml
+++ b/.github/workflows/Invalidations.yml
@@ -1,40 +1,71 @@
-name: Invalidations
+name: "Invalidations Check"
 
 on:
-  pull_request:
+  workflow_call:
+    inputs:
+      run-on-non-default-branches:
+        description: "Run on branches that are not the default branch as well"
+        default: false
+        required: false
+        type: boolean
+      directory:
+        description: "The directory on which JuliaFormatter needs to be run"
+        default: "."
+        required: false
+        type: string
+      julia-version:
+        description: "Julia version"
+        default: "1"
+        required: false
+        type: string
+      concurrent-jobs:
+        description: "Run jobs concurrently"
+        default: false
+        required: false
+        type: boolean
+      cancel-in-progress:
+        description: "Cancel jobs in-progress in favor of a new one in the same concurrency group"
+        default: true
+        required: false
+        type: boolean
 
 concurrency:
-  # Skip intermediate builds: always.
-  # Cancel intermediate builds: always.
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+  group: "${{ inputs.concurrent-jobs && github.run_id || github.ref  }}:${{ github.workflow }}"
+  cancel-in-progress: ${{ !inputs.concurrent-jobs && inputs.cancel-in-progress }}
 
 jobs:
-  evaluate:
-    # Only run on PRs to the default branch.
-    # In the PR trigger above branches can be specified only explicitly whereas this check should work for master, main, or any other default branch
-    if: github.base_ref == github.event.repository.default_branch
+  evaluate-invalidations:
+    if: ${{ inputs.run-on-non-default-branches || github.base_ref == github.event.repository.default_branch }}
     runs-on: ubuntu-latest
     steps:
-    - uses: julia-actions/setup-julia@v1
+    - uses: julia-actions/setup-julia@v2
       with:
-        version: '1'
-    - uses: actions/checkout@v3
-    - uses: julia-actions/julia-buildpkg@v1
-    - uses: julia-actions/julia-invalidations@v1
-      id: invs_pr
+        version: '${{ inputs.julia-version }}'
 
-    - uses: actions/checkout@v3
+    - name: "Checkout ${{ github.repository }}#${{ github.head_ref || github.ref_name }}"
+      uses: actions/checkout@v4
+    - uses: julia-actions/julia-buildpkg@v1
+    - name: "Count invalidations in PR"
+      id: invalidations-in-pr
+      uses: julia-actions/julia-invalidations@v1
+
+    - name: "Checkout ${{ github.repository }}#${{ github.event.repository.default_branch }}"
+      uses: actions/checkout@v4
       with:
-        ref: ${{ github.event.repository.default_branch }}
+        ref: "${{ github.event.repository.default_branch }}"
     - uses: julia-actions/julia-buildpkg@v1
-    - uses: julia-actions/julia-invalidations@v1
-      id: invs_default
+    - name: "Count baseline invalidations"
+      id: invalidations-baseline
+      uses: julia-actions/julia-invalidations@v1
 
-    - name: Report invalidation counts
+    - name: "Report invalidation counts"
       run: |
-        echo "Invalidations on default branch: ${{ steps.invs_default.outputs.total }} (${{ steps.invs_default.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
-        echo "This branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
-    - name: Check if the PR does increase number of invalidations
-      if: steps.invs_pr.outputs.total > steps.invs_default.outputs.total
-      run: exit 1
+        echo "Invalidations on ${{ github.event.repository.default_branch }}: ${{ steps.invalidations-baseline.outputs.total }} (${{ steps.invalidations-baseline.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
+        echo "Invalidations on ${{ github.head_ref || github.ref_name }}: ${{ steps.invalidations-in-pr.outputs.total }} (${{ steps.invalidations-in-pr.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
+
+    - name: "Check if the PR increases the number of invalidations"
+      run: |
+        if [ ${{ steps.invalidations-in-pr.outputs.total }} -gt ${{ steps.invalidations-baseline.outputs.total }} ]; then
+          echo "More invalidations have been introduced."
+          exit 1
+        fi
